### ISSUE TITLE
ENODEV

### ISSUE THREAD

**Issue by choucavalier** [adamjezek98/MPU6050-ESP8266-MicroPython#2]
Is this code still working?

I'm new to the whole esp8266 thing. I got a mpu6050 plugged to a wemos d1 mini. From the cabling side, everything looks right: wemos d1 mini turned on, mpu6050 turned on (inferring this from the led being turned on).

When trying to create an instance of the accelorometer class you implemented I get the following error:

```
>>> mpu6050.accel(i2c)                  
Traceback (most recent call last):      
  File "<stdin>", line 1, in <module>   
  File "mpu6050.py", line 6, in __init__
OSError: [Errno 19] ENODEV             
``` 

I'm not sure I understand how your code works (with the memory addresses and all)

```python
def __init__(self, i2c, addr=0x68):               
  self.iic = i2c                                  
  self.addr = addr                                
  self.iic.start()                                
  self.iic.writeto(self.addr, bytearray([107, 0]))
  self.iic.stop()                                 
```

The `self.iic.writeto(self.addr, bytearray([107, 0]))` instruction fails but I don't know why exactly.

Do you mind sharing some insights? :) Thanks!

**Comment by adamjezek98** [comment]
I think that the error means that there is no device at this address. Try some [IIC scanner ](https://gist.github.com/projetsdiy/f4330be62589ab9b3da1a4eacc6b6b1c)to see, if the MPU6050 is really working.
Also, if you have breakout board, they usually run on 5V and have resistors to take it down to 3.3V, as the MPU chip itself is 3.3V and get's fried at 5V, so not all of these boards can run on 3.3V.
When I was using some boards, I had to use a level shifter to shift IIC bus to 5V and power the board with 5V, otherwise, it didn't work.

**Comment by choucavalier** [comment]
Thank you for your reply. I'm actually working on it right now and got it to work. There was a soldering issue! Your code indeed works.

Do you know how to adjust the sensibility / update frequency of the sensor ?
