### ISSUE TITLE
OSError: I2C operation not supported

### ISSUE THREAD

**Issue by sahiljhawar** [adamjezek98/MPU6050-ESP8266-MicroPython#6]
While using the MPU6050, I am getting this error 
`Traceback (most recent call last):`
`File "<stdin>", line 4, in <module>`
`File "mpu6050.py", line 8, in __init__`
`OSError: I2C operation not supported`

**Comment by karlberggren** [comment]
I'm getting the same error, admittedly on an ESP32 rather than 8266, so maybe it just isn't compatible. 

It also seems like the error is probably somehow an interaction with the i2c library...  maybe the i2c library has been updated recently?

Edit: The problem seems to be in i2c.start() in the __init__ method.
>>> i2c.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: I2C operation not supported

So really, the problem does seem to be that the i2c library is not being called correctly (or similar).

**Comment by karlberggren** [comment]
OK, I resolve the problem by simply commenting out all the .start() and .stop() commands in the library.  My sense is that these are required for software simulated i2c, but not for hardware simulated i2c as is available on the ESP32.  Perhaps the 8266 had different requirements.  So for me, anyway, the problem is resolved.

**Comment by Dav-shell** [comment]
It worked. Thanks.
